import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-foodservice-distributor-rebate-recovery",
  "engine": "recovery",
  "title": "Foodservice Distributor Rebate & Allowance Recovery",
  "shortTitle": "Foodservice Rebate Recovery",
  "tagline": "Calculate every earned rebate, deviated-price allowance, incentive, and supplier credit",
  "industry": "Foodservice Channel Finance",
  "uiPort": 4579,
  "apiPort": 5579,
  "accent": "#15803d",
  "currency": "USD",
  "primaryOutcome": "Earned foodservice rebates and allowances claimed, collected, and reconciled to category economics",
  "valueNarrative": "Connect supplier agreements, items, purchases, tiers, growth, promotions, freight, accruals, statements, claims, and credits.",
  "calculation": {
    "actualKey": "receivedRebate",
    "expectedKey": "earnedRebate",
    "actualLabel": "Received Rebate & Credits",
    "expectedLabel": "Calculated Earned Rebate",
    "varianceLabel": "Unrecovered supported value",
    "direction": "expected-minus-actual",
    "finding": "Purchase volume, agreement tiers, allowance rules, and supplier statements indicate uncollected foodservice rebate value.",
    "actions": [
      "Validate the governing agreement and effective rules",
      "Reconcile transaction-level source evidence",
      "Prepare and submit the recovery or correction package",
      "Track response and reconcile realized financial outcome"
    ]
  }
},[
feature("supplier-agreement-library","FRR01","Supplier agreement library","Reconcile supplier agreement library using supplier agreements, item masters, purchase receipts, volume tiers, growth incentives, deviated pricing, promotions, freight allowances, accruals, statements, and credits.","Produce a governed supplier agreement library decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["supplierProgram","Supplier / Program","text","Harvest Foods / FY26 Growth Program"],["caseReference","Supplier agreement library Reference","text","FRR01-2026-001"],["receivedRebate","Received Rebate & Credits","currency",864000],["earnedRebate","Calculated Earned Rebate","currency",1125000],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedRebate",subjects:["Broadline distributor program","Protein supplier rebate","Beverage allowance","Produce growth incentive","Private-label conversion"]}),
feature("item-and-category-master","FRR02","Item and category master","Reconcile item and category master using supplier agreements, item masters, purchase receipts, volume tiers, growth incentives, deviated pricing, promotions, freight allowances, accruals, statements, and credits.","Produce a governed item and category master decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["supplierProgram","Supplier / Program","text","Harvest Foods / FY26 Growth Program"],["caseReference","Item and category master Reference","text","FRR02-2026-001"],["receivedRebate","Received Rebate & Credits","currency",864000],["earnedRebate","Calculated Earned Rebate","currency",1125000],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedRebate",subjects:["Broadline distributor program","Protein supplier rebate","Beverage allowance","Produce growth incentive","Private-label conversion"]}),
feature("purchase-and-receipt-ingestion","FRR03","Purchase and receipt ingestion","Reconcile purchase and receipt ingestion using supplier agreements, item masters, purchase receipts, volume tiers, growth incentives, deviated pricing, promotions, freight allowances, accruals, statements, and credits.","Produce a governed purchase and receipt ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["supplierProgram","Supplier / Program","text","Harvest Foods / FY26 Growth Program"],["caseReference","Purchase and receipt ingestion Reference","text","FRR03-2026-001"],["receivedRebate","Received Rebate & Credits","currency",864000],["earnedRebate","Calculated Earned Rebate","currency",1125000],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedRebate",subjects:["Broadline distributor program","Protein supplier rebate","Beverage allowance","Produce growth incentive","Private-label conversion"]}),
feature("volume-tier-qualification","FRR04","Volume-tier qualification","Reconcile volume-tier qualification using supplier agreements, item masters, purchase receipts, volume tiers, growth incentives, deviated pricing, promotions, freight allowances, accruals, statements, and credits.","Produce a governed volume-tier qualification decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["supplierProgram","Supplier / Program","text","Harvest Foods / FY26 Growth Program"],["caseReference","Volume-tier qualification Reference","text","FRR04-2026-001"],["receivedRebate","Received Rebate & Credits","currency",864000],["earnedRebate","Calculated Earned Rebate","currency",1125000],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedRebate",subjects:["Broadline distributor program","Protein supplier rebate","Beverage allowance","Produce growth incentive","Private-label conversion"]}),
feature("growth-incentive-calculation","FRR05","Growth incentive calculation","Reconcile growth incentive calculation using supplier agreements, item masters, purchase receipts, volume tiers, growth incentives, deviated pricing, promotions, freight allowances, accruals, statements, and credits.","Produce a governed growth incentive calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["supplierProgram","Supplier / Program","text","Harvest Foods / FY26 Growth Program"],["caseReference","Growth incentive calculation Reference","text","FRR05-2026-001"],["receivedRebate","Received Rebate & Credits","currency",864000],["earnedRebate","Calculated Earned Rebate","currency",1125000],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedRebate",subjects:["Broadline distributor program","Protein supplier rebate","Beverage allowance","Produce growth incentive","Private-label conversion"]}),
feature("deviated-pricing-reconciliation","FRR06","Deviated pricing reconciliation","Reconcile deviated pricing reconciliation using supplier agreements, item masters, purchase receipts, volume tiers, growth incentives, deviated pricing, promotions, freight allowances, accruals, statements, and credits.","Produce a governed deviated pricing reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["supplierProgram","Supplier / Program","text","Harvest Foods / FY26 Growth Program"],["caseReference","Deviated pricing reconciliation Reference","text","FRR06-2026-001"],["receivedRebate","Received Rebate & Credits","currency",864000],["earnedRebate","Calculated Earned Rebate","currency",1125000],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedRebate",subjects:["Broadline distributor program","Protein supplier rebate","Beverage allowance","Produce growth incentive","Private-label conversion"]}),
feature("new-location-allowance-tracking","FRR07","New-location allowance tracking","Reconcile new-location allowance tracking using supplier agreements, item masters, purchase receipts, volume tiers, growth incentives, deviated pricing, promotions, freight allowances, accruals, statements, and credits.","Produce a governed new-location allowance tracking decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["supplierProgram","Supplier / Program","text","Harvest Foods / FY26 Growth Program"],["caseReference","New-location allowance tracking Reference","text","FRR07-2026-001"],["receivedRebate","Received Rebate & Credits","currency",864000],["earnedRebate","Calculated Earned Rebate","currency",1125000],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedRebate",subjects:["Broadline distributor program","Protein supplier rebate","Beverage allowance","Produce growth incentive","Private-label conversion"]}),
feature("promotional-allowance-calculation","FRR08","Promotional allowance calculation","Reconcile promotional allowance calculation using supplier agreements, item masters, purchase receipts, volume tiers, growth incentives, deviated pricing, promotions, freight allowances, accruals, statements, and credits.","Produce a governed promotional allowance calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["supplierProgram","Supplier / Program","text","Harvest Foods / FY26 Growth Program"],["caseReference","Promotional allowance calculation Reference","text","FRR08-2026-001"],["receivedRebate","Received Rebate & Credits","currency",864000],["earnedRebate","Calculated Earned Rebate","currency",1125000],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedRebate",subjects:["Broadline distributor program","Protein supplier rebate","Beverage allowance","Produce growth incentive","Private-label conversion"]}),
feature("private-label-incentive-tracking","FRR09","Private-label incentive tracking","Reconcile private-label incentive tracking using supplier agreements, item masters, purchase receipts, volume tiers, growth incentives, deviated pricing, promotions, freight allowances, accruals, statements, and credits.","Produce a governed private-label incentive tracking decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["supplierProgram","Supplier / Program","text","Harvest Foods / FY26 Growth Program"],["caseReference","Private-label incentive tracking Reference","text","FRR09-2026-001"],["receivedRebate","Received Rebate & Credits","currency",864000],["earnedRebate","Calculated Earned Rebate","currency",1125000],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedRebate",subjects:["Broadline distributor program","Protein supplier rebate","Beverage allowance","Produce growth incentive","Private-label conversion"]}),
feature("freight-and-fuel-allowance-audit","FRR10","Freight and fuel allowance audit","Reconcile freight and fuel allowance audit using supplier agreements, item masters, purchase receipts, volume tiers, growth incentives, deviated pricing, promotions, freight allowances, accruals, statements, and credits.","Produce a governed freight and fuel allowance audit decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["supplierProgram","Supplier / Program","text","Harvest Foods / FY26 Growth Program"],["caseReference","Freight and fuel allowance audit Reference","text","FRR10-2026-001"],["receivedRebate","Received Rebate & Credits","currency",864000],["earnedRebate","Calculated Earned Rebate","currency",1125000],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedRebate",subjects:["Broadline distributor program","Protein supplier rebate","Beverage allowance","Produce growth incentive","Private-label conversion"]}),
feature("rebate-accrual-accounting","FRR11","Rebate accrual accounting","Reconcile rebate accrual accounting using supplier agreements, item masters, purchase receipts, volume tiers, growth incentives, deviated pricing, promotions, freight allowances, accruals, statements, and credits.","Produce a governed rebate accrual accounting decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["supplierProgram","Supplier / Program","text","Harvest Foods / FY26 Growth Program"],["caseReference","Rebate accrual accounting Reference","text","FRR11-2026-001"],["receivedRebate","Received Rebate & Credits","currency",864000],["earnedRebate","Calculated Earned Rebate","currency",1125000],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedRebate",subjects:["Broadline distributor program","Protein supplier rebate","Beverage allowance","Produce growth incentive","Private-label conversion"]}),
feature("supplier-statement-matching","FRR12","Supplier statement matching","Reconcile supplier statement matching using supplier agreements, item masters, purchase receipts, volume tiers, growth incentives, deviated pricing, promotions, freight allowances, accruals, statements, and credits.","Produce a governed supplier statement matching decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["supplierProgram","Supplier / Program","text","Harvest Foods / FY26 Growth Program"],["caseReference","Supplier statement matching Reference","text","FRR12-2026-001"],["receivedRebate","Received Rebate & Credits","currency",864000],["earnedRebate","Calculated Earned Rebate","currency",1125000],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedRebate",subjects:["Broadline distributor program","Protein supplier rebate","Beverage allowance","Produce growth incentive","Private-label conversion"]}),
feature("claim-generation","FRR13","Claim generation","Reconcile claim generation using supplier agreements, item masters, purchase receipts, volume tiers, growth incentives, deviated pricing, promotions, freight allowances, accruals, statements, and credits.","Produce a governed claim generation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["supplierProgram","Supplier / Program","text","Harvest Foods / FY26 Growth Program"],["caseReference","Claim generation Reference","text","FRR13-2026-001"],["receivedRebate","Received Rebate & Credits","currency",864000],["earnedRebate","Calculated Earned Rebate","currency",1125000],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedRebate",subjects:["Broadline distributor program","Protein supplier rebate","Beverage allowance","Produce growth incentive","Private-label conversion"]}),
feature("supplier-response-management","FRR14","Supplier response management","Reconcile supplier response management using supplier agreements, item masters, purchase receipts, volume tiers, growth incentives, deviated pricing, promotions, freight allowances, accruals, statements, and credits.","Produce a governed supplier response management decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["supplierProgram","Supplier / Program","text","Harvest Foods / FY26 Growth Program"],["caseReference","Supplier response management Reference","text","FRR14-2026-001"],["receivedRebate","Received Rebate & Credits","currency",864000],["earnedRebate","Calculated Earned Rebate","currency",1125000],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedRebate",subjects:["Broadline distributor program","Protein supplier rebate","Beverage allowance","Produce growth incentive","Private-label conversion"]}),
feature("credit-and-cash-reconciliation","FRR15","Credit and cash reconciliation","Reconcile credit and cash reconciliation using supplier agreements, item masters, purchase receipts, volume tiers, growth incentives, deviated pricing, promotions, freight allowances, accruals, statements, and credits.","Produce a governed credit and cash reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["supplierProgram","Supplier / Program","text","Harvest Foods / FY26 Growth Program"],["caseReference","Credit and cash reconciliation Reference","text","FRR15-2026-001"],["receivedRebate","Received Rebate & Credits","currency",864000],["earnedRebate","Calculated Earned Rebate","currency",1125000],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedRebate",subjects:["Broadline distributor program","Protein supplier rebate","Beverage allowance","Produce growth incentive","Private-label conversion"]}),
feature("supplier-and-category-yield-analytics","FRR16","Supplier and category yield analytics","Reconcile supplier and category yield analytics using supplier agreements, item masters, purchase receipts, volume tiers, growth incentives, deviated pricing, promotions, freight allowances, accruals, statements, and credits.","Produce a governed supplier and category yield analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["supplierProgram","Supplier / Program","text","Harvest Foods / FY26 Growth Program"],["caseReference","Supplier and category yield analytics Reference","text","FRR16-2026-001"],["receivedRebate","Received Rebate & Credits","currency",864000],["earnedRebate","Calculated Earned Rebate","currency",1125000],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedRebate",subjects:["Broadline distributor program","Protein supplier rebate","Beverage allowance","Produce growth incentive","Private-label conversion"]})
]);
